// Multi4Script.cpp -- reconstruction of a shipped mission script.
//
// Generated by tools/gen_mission.py from the shipped bytes, then verified against them
// with tools/sbs_diff.py. See probes/src/Multi12Script.cpp for the three traps this
// depends on (build flags, .text ordering, string-pool creation order).
//
// Build: -proc gekko -O4 -nodefaults -fp hard -Cpp_exceptions on -enum int -RTTI on -inline all -use_lmw_stmw on -wchar_t off

static const char *const kClassName = "Multi4Script";
static const char *const kBaseName  = "SPMission";

namespace MissionUtility
{
    int   AddObjective(const char*);
    void  PlayMusic(const char*, bool);
    void  SetEnemies(int, int);
    void  SetMapZoom(float, float);
    void  SetMusicLooping(bool);
    void  StartAmbiences(const char*, const char*, float, float);
}

class DLLBase
{
public:
    // Six vtable slots, read out of __vt__7DLLBase (0x8035ae5c, 24 B) and
    // __vt__9SPMission (0x8035ae3c, 32 B) -- see analysis/mission_script_abi.md.
    // A script never calls its own virtuals, so getting this wrong left every byte of
    // .text intact; it is .data that catches it -- tools/verify_vtables.py.
    virtual ~DLLBase() {}                 // +0x08
    virtual void InitialSetup();          // +0x0c  DLLBase::InitialSetup, 4 B, blr
    virtual bool Load();                  // +0x10  DLLBase::Load, 8 B, `return true`
    virtual void Execute();               // +0x14  DLLBase::Execute, 4 B, blr
};

class SPMission : public DLLBase
{
public:
    SPMission();
    virtual ~SPMission() {}                       // +0x08
    // SPMission::InitialSetup (0x801887b8, 200 B) zeroes the bool block, fills the float
    // block with 99999.0f, zeroes both int blocks, and only then calls slot +0x18 -- this
    // script's Setup. So a mission's start state is defined: every latch Setup does not
    // mention is false on the first tick.
    virtual void InitialSetup();                  // +0x0c  overrides DLLBase's
    virtual void Execute() = 0;                   // +0x14  re-declared pure; slot is null
    virtual void Setup() = 0;                     // +0x18  first slot SPMission adds
    virtual void RestartMission(int);             // +0x1c  0x801885bc, 4 B, blr

    bool  *mBools;    int mBoolCount;    // +0x04 +0x08
    int   *mIntsB;    int mCountB;       // +0x0c +0x10
    int   *mIntsC;    int mCountC;       // +0x14 +0x18
    void  *mBlockD;   int mCountD;       // +0x1c +0x20
};

class Multi4Script : public SPMission
{
public:
    virtual ~Multi4Script();

    Multi4Script()
    {
        mBoolCount = 1;   mBools    = &mDone;
        mCountB    = 0;   mIntsB    = mIntsBStore;
        mCountC    = 7;   mIntsC    = mIntsCStore;
        mCountD    = 0;   mBlockD   = &mBlockDStore;
    }

    virtual void Setup();
    virtual void Execute();

    char  mPad24;
    bool  mDone;                     // +0x25
    char  mPad26[6];
    int   mIntsBStore[2];           // +0x2c
    int   mIntsCStore[9];           // +0x34
    int   mBlockDStore;              // +0x58
};

Multi4Script::~Multi4Script()
{
}

void Multi4Script::Execute()
{
    if (mDone) {
        return;
    }

    MissionUtility::SetMusicLooping(true);
    MissionUtility::PlayMusic("EP2_V1_T12_01", true);
    MissionUtility::StartAmbiences("AmbKshyk_forestday01",
                                   "amb_kashyyk_day_stinger01",
                                   10.0f,
                                   30.0f);
    MissionUtility::AddObjective("multiplayer.types.deathmatch.rule01");
    MissionUtility::AddObjective("multiplayer.types.deathmatch.rule02");
    MissionUtility::SetMapZoom(900.0f, 10000.0f);
    MissionUtility::SetEnemies(1, 5);
    MissionUtility::SetEnemies(2, 5);
    MissionUtility::SetEnemies(3, 5);
    MissionUtility::SetEnemies(4, 5);

    mDone = true;
}

void Multi4Script::Setup()
{
    mDone = false;
}

SPMission *Multi4BuildMission()
{
    return new Multi4Script();
}
