/* glue_fallback.c -- GENERATED by tools/gc_bind.py; do not edit.
 * Builds without the recovered source: each hooked function is its translation. */
extern void sub_00177426_gen(void);
void sub_00177426(void) { sub_00177426_gen(); }
extern void sub_001774A8_gen(void);
void sub_001774A8(void) { sub_001774A8_gen(); }
extern void sub_0017B46A_gen(void);
void sub_0017B46A(void) { sub_0017B46A_gen(); }
extern void sub_0017B4AB_gen(void);
void sub_0017B4AB(void) { sub_0017B4AB_gen(); }
extern void sub_0017B56D_gen(void);
void sub_0017B56D(void) { sub_0017B56D_gen(); }
extern void sub_0017BBC0_gen(void);
void sub_0017BBC0(void) { sub_0017BBC0_gen(); }
extern void sub_0017C213_gen(void);
void sub_0017C213(void) { sub_0017C213_gen(); }
extern void sub_0017C866_gen(void);
void sub_0017C866(void) { sub_0017C866_gen(); }
extern void sub_0017CEBD_gen(void);
void sub_0017CEBD(void) { sub_0017CEBD_gen(); }
extern void sub_0017CF30_gen(void);
void sub_0017CF30(void) { sub_0017CF30_gen(); }
extern void sub_0017CFB2_gen(void);
void sub_0017CFB2(void) { sub_0017CFB2_gen(); }
extern void sub_0017D19F_gen(void);
void sub_0017D19F(void) { sub_0017D19F_gen(); }
extern void sub_0017DC4D_gen(void);
void sub_0017DC4D(void) { sub_0017DC4D_gen(); }
extern void sub_0017DD32_gen(void);
void sub_0017DD32(void) { sub_0017DD32_gen(); }
extern void sub_0017DE2A_gen(void);
void sub_0017DE2A(void) { sub_0017DE2A_gen(); }
extern void sub_0017DF1A_gen(void);
void sub_0017DF1A(void) { sub_0017DF1A_gen(); }
extern void sub_0017E08E_gen(void);
void sub_0017E08E(void) { sub_0017E08E_gen(); }
extern void sub_0017E20B_gen(void);
void sub_0017E20B(void) { sub_0017E20B_gen(); }
extern void sub_0017E302_gen(void);
void sub_0017E302(void) { sub_0017E302_gen(); }
extern void sub_0017E423_gen(void);
void sub_0017E423(void) { sub_0017E423_gen(); }
extern void sub_0017E449_gen(void);
void sub_0017E449(void) { sub_0017E449_gen(); }
extern void sub_0017E72D_gen(void);
void sub_0017E72D(void) { sub_0017E72D_gen(); }
extern void sub_0017EED6_gen(void);
void sub_0017EED6(void) { sub_0017EED6_gen(); }
extern void sub_0017F67B_gen(void);
void sub_0017F67B(void) { sub_0017F67B_gen(); }
extern void sub_0017FE20_gen(void);
void sub_0017FE20(void) { sub_0017FE20_gen(); }
extern void sub_001805C5_gen(void);
void sub_001805C5(void) { sub_001805C5_gen(); }
extern void sub_0018082B_gen(void);
void sub_0018082B(void) { sub_0018082B_gen(); }
extern void sub_001808CE_gen(void);
void sub_001808CE(void) { sub_001808CE_gen(); }
extern void sub_00180C98_gen(void);
void sub_00180C98(void) { sub_00180C98_gen(); }
extern void sub_00180DAB_gen(void);
void sub_00180DAB(void) { sub_00180DAB_gen(); }
extern void sub_00180E90_gen(void);
void sub_00180E90(void) { sub_00180E90_gen(); }
extern void sub_00180F94_gen(void);
void sub_00180F94(void) { sub_00180F94_gen(); }
extern void sub_00181276_gen(void);
void sub_00181276(void) { sub_00181276_gen(); }
extern void sub_001815FE_gen(void);
void sub_001815FE(void) { sub_001815FE_gen(); }
extern void sub_00187FA7_gen(void);
void sub_00187FA7(void) { sub_00187FA7_gen(); }
extern void sub_00188757_gen(void);
void sub_00188757(void) { sub_00188757_gen(); }
extern void sub_00196159_gen(void);
void sub_00196159(void) { sub_00196159_gen(); }
extern void sub_00196BD0_gen(void);
void sub_00196BD0(void) { sub_00196BD0_gen(); }
extern void sub_001A2F6B_gen(void);
void sub_001A2F6B(void) { sub_001A2F6B_gen(); }
extern void sub_001A3D2F_gen(void);
void sub_001A3D2F(void) { sub_001A3D2F_gen(); }
extern void sub_001AE777_gen(void);
void sub_001AE777(void) { sub_001AE777_gen(); }
extern void sub_001AEE6D_gen(void);
void sub_001AEE6D(void) { sub_001AEE6D_gen(); }
extern void sub_001B8EAB_gen(void);
void sub_001B8EAB(void) { sub_001B8EAB_gen(); }
extern void sub_001B94FE_gen(void);
void sub_001B94FE(void) { sub_001B94FE_gen(); }
extern void sub_001C2C28_gen(void);
void sub_001C2C28(void) { sub_001C2C28_gen(); }
extern void sub_001C31BC_gen(void);
void sub_001C31BC(void) { sub_001C31BC_gen(); }
extern void sub_001C9247_gen(void);
void sub_001C9247(void) { sub_001C9247_gen(); }
extern void sub_001C9D35_gen(void);
void sub_001C9D35(void) { sub_001C9D35_gen(); }
extern void sub_001D8EF2_gen(void);
void sub_001D8EF2(void) { sub_001D8EF2_gen(); }
extern void sub_001D9E10_gen(void);
void sub_001D9E10(void) { sub_001D9E10_gen(); }
extern void sub_001E273D_gen(void);
void sub_001E273D(void) { sub_001E273D_gen(); }
extern void sub_001E2D6E_gen(void);
void sub_001E2D6E(void) { sub_001E2D6E_gen(); }
extern void sub_001EA96F_gen(void);
void sub_001EA96F(void) { sub_001EA96F_gen(); }
extern void sub_001EB523_gen(void);
void sub_001EB523(void) { sub_001EB523_gen(); }
extern void sub_001F5839_gen(void);
void sub_001F5839(void) { sub_001F5839_gen(); }
extern void sub_001F5F8D_gen(void);
void sub_001F5F8D(void) { sub_001F5F8D_gen(); }
extern void sub_001FDA41_gen(void);
void sub_001FDA41(void) { sub_001FDA41_gen(); }
extern void sub_001FDF34_gen(void);
void sub_001FDF34(void) { sub_001FDF34_gen(); }
extern void sub_002081EF_gen(void);
void sub_002081EF(void) { sub_002081EF_gen(); }
extern void sub_00208E97_gen(void);
void sub_00208E97(void) { sub_00208E97_gen(); }
extern void sub_00214299_gen(void);
void sub_00214299(void) { sub_00214299_gen(); }
extern void sub_00214645_gen(void);
void sub_00214645(void) { sub_00214645_gen(); }
extern void sub_0021B578_gen(void);
void sub_0021B578(void) { sub_0021B578_gen(); }
extern void sub_0021B751_gen(void);
void sub_0021B751(void) { sub_0021B751_gen(); }
