/**
 * Star Wars: The Clone Wars - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - CLONEWARS_ENTRY_POINT is the XBE entry point address
 *   - The XBE and game data are found beside the .exe (see resolve_dirs)
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (from tools.xbe_parser):
 *   Title:       SW: The Clone Wars
 *   Title ID:    0x4C410004  (LucasArts)
 *   Type:        Retail, DVD_X2, NTSC North America
 *   Build:       2003-04-04, XDK 5233
 *   Base addr:   0x00010000
 *   Entry point: 0x00160EBA
 *   Image size:  0x006334E0 (6.20 MB)
 *   Code size:   2631.5 KB (.text) + 9 linked XDK code sections
 *   Sections:    18 (.text, XNET, XONLINE, D3D, D3DX, DSOUND, XMV, XGRPH,
 *                XPP, .rdata, .data, XON_RD, DOLBY, .data1, $$XTINFO,
 *                $$XTIMAGE, $$XSIMAGE, .XTLID)
 *   Kernel imports: 142
 */

#include <windows.h>
/* Host instruction/stack pointer of an exception context, either width. */
#if defined(_M_IX86)
#define CTX_IP(c) ((uintptr_t)(c)->Eip)
#define CTX_SP(c) ((uintptr_t)(c)->Esp)
#else
#define CTX_IP(c) ((uintptr_t)(c)->Rip)
#define CTX_SP(c) ((uintptr_t)(c)->Rsp)
#endif
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

#define CLONEWARS_ENTRY_POINT   0x00160EBA   /* XBE entry point VA */
#define CLONEWARS_XBE_NAME      "default.xbe"

/* Saves land under %LOCALAPPDATA%. The runtime's own default is a shared
 * "xboxrecomp" folder that every title would write into, so name ours. */
#define CLONEWARS_SAVE_SUBDIR   "CloneWarsRecomp"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);
static void resolve_dirs(char *game_dir, char *xbe_path, char *save_dir,
                        size_t n);
static void configure_host_log(void);

/* Recompiled entry point (generated by the recomp pipeline).
 *
 * Lifted functions are otherwise named after their guest address
 * (sub_00160E46 and so on), but the entry point is the one exception: the
 * disassembler labels it xbe_entry_point in functions.json, and the lifter
 * emits that name. Here it is defined in gen/recomp_0006.c. */
extern void xbe_entry_point(void);

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host RIP and nothing else -- there is no guest program counter to
 * report, and the host address changes every build. Two things recover the
 * guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the linker's PDB already maps host address back to guest
 *     function. dbghelp turns an anonymous RIP into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires linking dbghelp and keeping the .pdb beside the .exe.
 */
static void print_guest_context(void *rip)
{
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);
    {
        /* The generated C line: its comments carry the guest address. */
        IMAGEHLP_LINE64 line;
        DWORD ldisp = 0;
        memset(&line, 0, sizeof line);
        line.SizeOfStruct = sizeof line;
        if (SymGetLineFromAddr64(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &ldisp, &line))
            fprintf(stderr, "  at %s:%lu\n", line.FileName, (unsigned long)line.LineNumber);
    }

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
    }
}

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)CTX_IP(ep->ContextRecord),
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));
        print_guest_context((void *)CTX_IP(ep->ContextRecord));

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)CTX_SP(ep->ContextRecord);
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── WinMain ───────────────────────────────────────────────── */

/* See RECOMP_PROTECT_RDATA in main(). */
static uintptr_t s_rdata_page;
static __declspec(thread) int s_rdata_stepping;

static LONG CALLBACK rdata_watch_veh(PEXCEPTION_POINTERS ep)
{
    PEXCEPTION_RECORD er = ep->ExceptionRecord;
    DWORD old_prot;

    if (er->ExceptionCode == EXCEPTION_SINGLE_STEP && s_rdata_stepping) {
        s_rdata_stepping = 0;
        VirtualProtect((void *)s_rdata_page, 0x1000, PAGE_READONLY, &old_prot);
        return EXCEPTION_CONTINUE_EXECUTION;
    }
    if (er->ExceptionCode == EXCEPTION_ACCESS_VIOLATION &&
        er->NumberParameters >= 2 && er->ExceptionInformation[0] == 1) {
        uintptr_t a = (uintptr_t)er->ExceptionInformation[1];
        uintptr_t table = (uintptr_t)g_xbox_mem_offset + 0x00334440u;
        if (a >= s_rdata_page && a < s_rdata_page + 0x1000) {
            if (a >= table && a < table + 142 * 4) {
                fprintf(stderr, "[RDATA] write into kernel thunk slot %u (guest 0x%08X)\n",
                        (unsigned)((a - table) / 4), (uint32_t)(a - (uintptr_t)g_xbox_mem_offset));
                fflush(stderr);
                return EXCEPTION_CONTINUE_SEARCH;   /* crash handler names the writer */
            }
            VirtualProtect((void *)s_rdata_page, 0x1000, PAGE_READWRITE, &old_prot);
            s_rdata_stepping = 1;
            ep->ContextRecord->EFlags |= 0x100;     /* trap after this one instruction */
            return EXCEPTION_CONTINUE_EXECUTION;
        }
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

/* CW_WATCH=<guest hex address>: hardware write watchpoint (DR0, 4 bytes) on
 * the game's main thread. Every write is logged with the host function that
 * did it and the guest call stack, so a corrupted field names its writer.
 * Diagnostic only. */
static uint32_t s_watch_va;
static HANDLE s_watch_thread;

static LONG CALLBACK watch_veh(PEXCEPTION_POINTERS ep)
{
    static unsigned hits;
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *si = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;
    if (ep->ExceptionRecord->ExceptionCode != EXCEPTION_SINGLE_STEP || !(ep->ContextRecord->Dr6 & 1))
        return EXCEPTION_CONTINUE_SEARCH;
    ep->ContextRecord->Dr6 = 0;
    if (++hits <= 400) {
        const uint32_t *sp = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int i, shown = 0;
        memset(buf, 0, sizeof buf);
        si->SizeOfStruct = sizeof(SYMBOL_INFO);
        si->MaxNameLen = 255;
        if (!SymFromAddr(GetCurrentProcess(), (DWORD64)CTX_IP(ep->ContextRecord), &disp, si))
            strcpy(si->Name, "?");
        fprintf(stderr, "[WATCH] #%u %08X <- %08X by %s+0x%llX stack:", hits, s_watch_va,
                *(uint32_t *)((uintptr_t)g_xbox_mem_offset + s_watch_va), si->Name,
                (unsigned long long)disp);
        for (i = 0; i < 64 && shown < 8; i++)
            if (sp[i] > g_xbox_code_lo && sp[i] < g_xbox_code_hi) { fprintf(stderr, " %08X", sp[i]); shown++; }
        fprintf(stderr, "\n");
        fflush(stderr);
    }
    return EXCEPTION_CONTINUE_EXECUTION;
}

static DWORD WINAPI watch_arm(LPVOID unused)
{
    CONTEXT c;
    (void)unused;
    memset(&c, 0, sizeof c);
    c.ContextFlags = CONTEXT_DEBUG_REGISTERS;
    SuspendThread(s_watch_thread);
    GetThreadContext(s_watch_thread, &c);
    c.Dr0 = (uintptr_t)g_xbox_mem_offset + s_watch_va;
    c.Dr7 = (c.Dr7 & ~0x000F0003u) | 1u | (1u << 16) | (3u << 18);   /* L0, write, 4 bytes */
    SetThreadContext(s_watch_thread, &c);
    ResumeThread(s_watch_thread);
    return 0;
}

static void watch_start(void)
{
    const char *w = getenv("CW_WATCH");
    HANDLE t;
    if (!w || !*w) return;
    s_watch_va = (uint32_t)strtoul(w, NULL, 16) & ~3u;
    DuplicateHandle(GetCurrentProcess(), GetCurrentThread(), GetCurrentProcess(),
                    &s_watch_thread, 0, FALSE, DUPLICATE_SAME_ACCESS);
    AddVectoredExceptionHandler(1, watch_veh);
    t = CreateThread(NULL, 0, watch_arm, NULL, 0, NULL);
    WaitForSingleObject(t, INFINITE);
    CloseHandle(t);
    fprintf(stderr, "[WATCH] armed on guest %08X\n", s_watch_va);
}

/* CW_SAMPLE_MAIN=1: every 5 s, name the function the game's main thread is
 * executing. A title that has stopped presenting frames without calling the
 * kernel is spinning somewhere in its own code; this says where. */
static HANDLE s_main_thread;

static DWORD WINAPI main_sampler(LPVOID unused)
{
    /* 100 samples a second; every 10 s print the top functions. */
    enum { SLOTS = 512 };
    static char names[SLOTS][64];
    static unsigned counts[SLOTS];
    unsigned total = 0, tick = 0;
    (void)unused;
    {
        /* CW_SAMPLE_DELAY=<seconds>: start sampling later. Sampling slows the
         * game thread, which changes what it is doing; delay it to the part
         * of the run being investigated. */
        const char *d = getenv("CW_SAMPLE_DELAY");
        if (d && atoi(d) > 0)
            Sleep((DWORD)atoi(d) * 1000u);
    }
    for (;;) {
        CONTEXT c;
        char buf[sizeof(SYMBOL_INFO) + 256];
        SYMBOL_INFO *si = (SYMBOL_INFO *)buf;
        DWORD64 disp = 0;
        int k;
        Sleep(10);
        memset(&c, 0, sizeof c);
        c.ContextFlags = CONTEXT_CONTROL;
        if (SuspendThread(s_main_thread) == (DWORD)-1)
            continue;
        GetThreadContext(s_main_thread, &c);
        ResumeThread(s_main_thread);
        memset(buf, 0, sizeof buf);
        si->SizeOfStruct = sizeof(SYMBOL_INFO);
        si->MaxNameLen = 255;
        if (!SymFromAddr(GetCurrentProcess(), (DWORD64)CTX_IP(&c), &disp, si))
            strcpy(si->Name, "?");
        for (k = 0; k < SLOTS; k++) {
            if (!names[k][0]) { strncpy(names[k], si->Name, 63); counts[k] = 1; break; }
            if (!strcmp(names[k], si->Name)) { counts[k]++; break; }
        }
        total++;
        if (++tick >= 1000) {
            int shown;
            fprintf(stderr, "  [SAMPLE] main thread, %u samples:", total);
            for (shown = 0; shown < 10; shown++) {
                int best = -1;
                for (k = 0; k < SLOTS && names[k][0]; k++)
                    if (counts[k] && (best < 0 || counts[k] > counts[best])) best = k;
                if (best < 0) break;
                fprintf(stderr, " %s=%u", names[best], counts[best]);
                counts[best] = 0;
            }
            fprintf(stderr, "\n");
            fflush(stderr);
            memset(names, 0, sizeof names);
            memset(counts, 0, sizeof counts);
            total = 0; tick = 0;
        }
    }
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;
    char game_dir[MAX_PATH], xbe_path[MAX_PATH], save_dir[MAX_PATH];

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    configure_host_log();

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== Star Wars: The Clone Wars - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    resolve_dirs(game_dir, xbe_path, save_dir, MAX_PATH);
    printf("Game directory: %s\n", game_dir);

    if (!load_xbe(xbe_path, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "This executable must sit in the game directory, beside "
                    "default.xbe, data.zwp and the Bins/Data/Movies folders.",
                    "Clone Wars Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(game_dir, save_dir);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", CLONEWARS_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    /* Step 7: Call the recompiled entry point */
    /* RECOMP_PROTECT_RDATA=1: catch stray writes to the kernel thunk table.
     *
     * The table sits at the start of .rdata, and a guest write that zeroes a
     * slot turns a kernel call into a silent null call. Its page is shared
     * with XPP's writable data, so the page is protected and every write to
     * it faults: writes outside the table are let through one instruction at
     * a time (rdata_watch_veh), and a write into the table falls through to
     * the crash handler, which names the writer. Diagnostic only. */
    if (getenv("RECOMP_PROTECT_RDATA")) {
        DWORD old_prot;
        s_rdata_page = (uintptr_t)g_xbox_mem_offset + 0x00334000u;
        AddVectoredExceptionHandler(1, rdata_watch_veh);
        printf("RECOMP_PROTECT_RDATA: thunk page read-only: %s\n",
               VirtualProtect((void *)s_rdata_page, 0x1000, PAGE_READONLY, &old_prot) ? "yes" : "FAILED");
    }

    printf("\nStarting game...\n");
    fflush(stdout);

    /* With the DX8 renderer drawing, the runtime's software NV2A only has to
     * consume the pushbuffer; rasterising it too starves the game thread. */
    if (getenv("CW_D3D8") && getenv("CW_D3D8")[0] == '1' && !getenv("RECOMP_PB_NORASTER"))
        _putenv("RECOMP_PB_NORASTER=1");
    if (getenv("CW_SAMPLE_MAIN")) {
        DuplicateHandle(GetCurrentProcess(), GetCurrentThread(), GetCurrentProcess(),
                        &s_main_thread, 0, FALSE, DUPLICATE_SAME_ACCESS);
        CloseHandle(CreateThread(NULL, 0, main_sampler, NULL, 0, NULL));
    }
    {
        extern void xbox_pin_guest_thread(int interrupt_level);
        xbox_pin_guest_thread(0);
    }
    watch_start();
    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* ── Directory resolution ──────────────────────────────────── */

/*
 * Everything the game reads sits beside the .exe: default.xbe, data.zwp,
 * config.ini and the Addon/Bins/Data/Movies folders. Deriving those paths from
 * the module filename rather than the current directory means the build
 * behaves the same however it is started -- double-clicked, from a shortcut,
 * or from a shell sitting somewhere else. The toolkit's own notes record the
 * alternative as "running from the wrong working directory", where every
 * asset load fails and nothing else says why.
 *
 * Saves go to %LOCALAPPDATA%\CloneWarsRecomp instead, so the game directory
 * stays exactly as it was dumped and saves cannot collide with another
 * recompiled title's.
 */
static void resolve_dirs(char *game_dir, char *xbe_path, char *save_dir,
                         size_t n)
{
    const char *appdata;
    const char *override = getenv("CW_GAME_DIR");
    char *slash;

    /* CW_GAME_DIR points the disc at a folder other than the exe's. The
     * title scans its whole disc at boot, so a development tree full of
     * sources and logs beside the exe costs minutes per run. */
    if (override && override[0]) {
        strncpy(game_dir, override, n);
        game_dir[n - 1] = '\0';
        slash = game_dir + strlen(game_dir);
        while (slash > game_dir && (slash[-1] == '\\' || slash[-1] == '/'))
            *--slash = '\0';
    } else if (GetModuleFileNameA(NULL, game_dir, (DWORD)n) == 0) {
        strncpy(game_dir, ".", n);
        game_dir[n - 1] = '\0';
    } else {
        slash = strrchr(game_dir, '\\');
        if (slash)
            *slash = '\0';
    }

    snprintf(xbe_path, n, "%s\\%s", game_dir, CLONEWARS_XBE_NAME);

    appdata = getenv("LOCALAPPDATA");
    if (appdata && appdata[0])
        snprintf(save_dir, n, "%s\\%s", appdata, CLONEWARS_SAVE_SUBDIR);
    else
        snprintf(save_dir, n, "%s\\SaveData", game_dir);
}

static void configure_host_log(void)
{
    const char *path = getenv("CW_HOST_LOG");
    if (!path || !*path)
        return;

    if (!freopen(path, "w", stdout))
        return;
    (void)freopen(path, "a", stderr);
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
